id: hl7.fhir.gr.base-and-core-r5
canonical: https://hl7-hellas.gr/fhir/hl7-fhir-gr-base-and-core-r5
fhirVersion: 5.0.0
name: HL7_FHIR_GR_BASE_AND_CORE
title: GR FHIR Base and Core Implementation Guide
description: This IG defines base and core HL7® FHIR®© profiles for the Greek context aligned with EU realm
status: draft
experimental: true
date: 2025-12-08
version: 0.0.1-draft
copyright: HL7 Hellas
copyrightYear: 2025+
releaseLabel: draft
publisher:
  name: HL7 Hellas
  url: https://hl7-hellas.gr/
contact:
  - name: HL7 Hellas
    telecom:
      - system: url
        value: https://hl7-hellas.gr/
license: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#GR

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 0
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: draft

dependencies:
  hl7.fhir.eu.base-r5: 0.1.0

pages:
  index.md:
    title: Home
  background.md:
    title: Background
  use-cases.md:
    title: Use cases
  logical-models.md:
    title: Logical models
  capability-statements.md:
    title: Capability statements
  downloads.md:
    title: Downloads
  support.md:
    title: Support
  glossary.md:
    title: Glossary
  changes.md:
    title: Change log

menu:
  Home: index.html
  Table of content: toc.html
  Background: background.html
  Use cases: use-cases.html
  Specification:
    Logical models: logical-models.html
    Artifacts: artifacts.html
    Capability statements: capability-statements.html
  Downloads: downloads.html
  Support: support.html
  Glossary: glossary.html
  Change log: changes.html

parameters:
  i18n-default-lang: en
  # include all for publishing, exclude for faster build time
  excludexml: false
  excludejson: false
  excludettl: false
  excludemap: false
  validation: [allow-any-extensions, no-broken-links]
  show-inherited-invariants: true
  usage-stats-opt-out: true

instanceOptions:
  setMetaProfile: always
  setId: standalone-only
  manualSliceOrdering: true

groups:
  GrBase:
    name: HL7 Hellas base profiles
    description: Base profiles for the Greece
    resources:
      - StructureDefinition/patient-base
      - Patient/Patient-With-Amka
  GrCore:
    name: HL7 Hellas core profiles
    description: Core profiles for the Greece
    resources:
      - StructureDefinition/greek-patient
      - Patient/George-Papadopoulos
      - Patient/No-Name-Patient
  Models:
    name: HL7 Hellas logical models
    description: Logical models for the Greece
    resources:
      - StructureDefinition/GreekIdentifier
      - StructureDefinition/GreekHumanName
      - StructureDefinition/GreekAddress
      - StructureDefinition/GreekContactPoint
      - StructureDefinition/GreekPatient
